### PR TITLE
Working build function.

### PR DESCRIPTION
**Pull request by s1eve-mcdichae1**
Fixed a typo.

Cleaned up some trailing spaces.

I guess `ret_require` needs "double quotes," not 'single.' (Edit: I guess it's not the function itself but the fact it uses a $variable in the path that requires double quotes; I've learned that double quotes allow var expansion while single quotes interpret them literally.)

Renamed file (repo and module are both named with `-evo`; file probably should be, too.)

-----

Got past the build phase, threw an error downloading the boss rush mod. Investigating now.

### CODE REVIEW

**Comment by Exarkuniv** [comment]
how the hell do you find the spaces? lol

**Comment by s1eve-mcdichae1** [comment]
> how the hell do you find the spaces? lol

Sometimes I just find them by accident when I click on a line, but this time I was editing the file in `nano` on my Pi, and trailing spaces are highlighted there.

Found the typo in the `download` command for boss_rush.zip (I had typed the wrong path, left out a dir. Also I think we don't need the filename here like I had initially, since I DID have to make the destination dir first, I can just point it at the dir and it will just read the filename from the URL -- and the destination dir *does* have to be created first or it apparently won't work.)

Still having a couple issues with escaping commands:

The binary builds, but when I run it, it says: `Error opening font file omdir/ports/CaveStory/d_id/data/font_1.fnt`. Clearly it's gonna take some extra fiddling to get the params to pass correctly and expand the vars. I'll post on the forum about it.

Also my:

    mv "$romdir/ports/CaveStory/$md_id/CaveStory/*" "$romdir/ports/CaveStory/$md_id"
 
 ...isn't working in the script, I suppose it's probably because the star is inside the quotes or something?

**Comment by Exarkuniv** [comment]
> Also my:
> 
> ```
> mv "$romdir/ports/CaveStory/$md_id/CaveStory/*" "$romdir/ports/CaveStory/$md_id"
> ```
> 
> ...isn't working in the script, I suppose it's probably because the star is inside the quotes or something?

possible, i think for something like that in the past (old school way) i use ``cp`` and just copyed it to the new folder. 
but now i dont know. im still in the mind set if it not broke dont fix it. lol, but im old so..:P

**Comment by s1eve-mcdichae1** [comment]
I think this is just about done. It installs and runs, with the language packs and sample mod.

Some of the depends may not be necessary.  I've compiled and run this without ever installing `libsdl2-gfx-dev`, for example. I did then install it as a test; the binary is identical with or without it so unless it makes some difference at run-time, I don't think we need that one. Maybe a couple others too, I'll ask the devs about it.

**Comment by Exarkuniv** [comment]
looks good, 
so how did you go about finding out what depends you needed and not needed
that list is what the devs told me, which is why it was there. 

and you know of a list or something that is already there from a clean retropie load? i cant go off of my test image since it already has things installed. 

i always feel like somethings dont need to be there

**Comment by s1eve-mcdichae1** [comment]
> looks good, so how did you go about finding out what depends you needed and not needed that list is what the devs told me, which is why it was there.

I started with what the wiki says:

`build-essential libpng-dev libjpeg-dev make cmake cmake-data git libsdl2-dev libsdl2-doc libsdl2-gfx-dev libsdl2-gfx-doc libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev`

Some of them were covered by the distro already (`build-essential`, `git`) or were deps of another package that we have or will have, (`cmake-data` comes with `cmake`, `make` comes with `build-essential`) or were docs. 

Some of the rest were mentioned in the build report when I build the makefiles with `cmake`:

```
-- Found SDL2: ...
-- Found SDL2_mixer: ...
-- Found SDL2_image: ...
-- Found ZLIB: ...
-- Found PNG: ...
-- Found JPEG: ...
```

That only left three packages I was unsure about, so I just [asked them](https://github.com/nxengine/nxengine-evo/issues/261) about the -gfx, -net, and -ttf packages. They said no:

> `libsdl2-doc libsdl2-gfx-dev libsdl2-gfx-doc libsdl2-net-dev libsdl2-ttf-dev` aren't needed. I'll fix wiki.
> zlib-dev is usually pulled in by libpng-dev

-----

> and you know of a list or something that is already there from a clean retropie load? i cant go off of my test image since it already has things installed.

I don't know if it's the full list, but I found this function in `scriptmodules/system.sh` which has at least some of them:

```
function get_retropie_depends() {
    local depends=(git subversion dialog curl gcc g++ build-essential unzip xmlstarlet python3-pyudev ca-certificates dirmngr)

    [[ -n "$DISTCC_HOSTS" ]] && depends+=(distcc)

    [[ "$__use_ccache" -eq 1 ]] && depends+=(ccache)

    if ! getDepends "${depends[@]}"; then
        fatalError "Unable to install packages required by $0 - ${md_ret_errors[@]}"
    fi

    # make sure we don't have xserver-xorg-legacy installed as it breaks launching x11 apps from ES
    if ! isPlatform "x11" && hasPackage "xserver-xorg-legacy"; then
        aptRemove xserver-xorg-legacy
    fi
}
```

> i always feel like somethings dont need to be there

You could always leave them out & wait for someone to say it don't work, haha! (Probably better to just ask someone, though.) :)

**Comment by Exarkuniv** [comment]
so by default we should not have ``build-essential, make, git`` in the depends.
and ``cmake`` i think we dont need, but i dont remember 

im slowly learning, :)

**Comment by s1eve-mcdichae1** [comment]
I think we do still need `cmake`, I see it in the depends of a lot of the default scripts that ship with RP already. But yeah, the other three are "hard deps" for the RetroPie distro, so you never need to include them in modules.

**Pull request merged**
