### PR TITLE
Streamlined and standardized a bit.

### PR DESCRIPTION
**Pull request by s1eve-mcdichae1**

### CODE REVIEW

**Comment by Exarkuniv** [comment]
Maybe you should just take over this from me. It seems you are a hell better at then me

**Comment by s1eve-mcdichae1** [comment]
I just learned by looking at the other modules and by asking mitu a ton of questions while developing my first module for gmloader. Have a look through the helper functions in https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/helpers.sh too, it can help make clearer some more of what's going on in the modules.

**Comment by Exarkuniv** [comment]
I'll never get the new way they do shit now. 
Took me over a year just to figure this way out. And now it seems that it's just worthless. 
Im always late to the party. 
Oh well.

**Comment by Exarkuniv** [comment]
It just annoys me a little that I asked for help too and I ask questions and no one there helped me at all. 

The only her he gave me was how to run the scripts. 

And now I find out that the way I'm making them is wrong. So what's the point if someone else is going to come in and redo it. 

Why waste all my time doing it. You know?

This has nothing against you. You happened to ask for help at the right time it seems so you learned the better way

**Comment by s1eve-mcdichae1** [comment]
Whoops I guess it doesn't like when you rename a branch that has an open PR.

**Comment by s1eve-mcdichae1** [comment]
Anyway, all I meant was to offer some suggestions. You may use them or not, as you please.

**Comment by Exarkuniv** [comment]
No I'm fine with useing them. 
I just wish there was more document on why this are certain ways. 

Like for one how many spaces after you start a line. 

I saw that you removed some. Why. 

The rest makes sense. 
Like the downloadandextract...like that I did not know anything about.

But the spaces. Like how many do you use?

**Comment by Exarkuniv** [comment]
And as for the saves and configs. I don't know. The devs over at nxengine-evo don't have anything in the docs about where that's included. 

I believe the old engine it's in with the game files. 

Once I get to work I can see what I see. And ask the devs if needed

**Comment by s1eve-mcdichae1** [comment]
> But the spaces. Like how many do you use?

I use four spaces per "level" of indent, but IMO it's less about "how many" than about being internally consistent. Some lines had three spaces, some had five; some had tabs...it was all over the place, I just cleaned it up so they were all the same. Traditionally, additional levels of indent would be used for subroutines, like the steps in a `while` loop for example, but there isn't really any of that here. But something like:

```
# no indent
function() {
    # one indent
    commands
    more commands
    while true; do
        # two indents
        things to do while true
        do more things while true
    done
    remaining commands
}
```

> And as for the saves and configs. I don't know. The devs over at nxengine-evo don't have anything in the docs about where that's included.

Wherever the saves end up, we'll want to link them to the `$md_conf_root` dir (`/opt/retropie/configs/ports`) for network share access (e.g. for backups) with a `moveConfigDir` (helper function: moves contents, then symlinks to the old location) into `$md_conf_root/cavestory`: https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/helpers.sh#L518

Also I see in one of the other discussions that the data files are expected to be found in (and therefore I assume `make install` moves them to) `/usr/share/bin`;

Ideally, we will probably want it installed in `/opt/retropie/ports`, if that can happen. I will have some time next week to look into the flags and commands to make this work; I suspect it will be some combination of using the "PORTABLE" build option (data files are expected in the same dir as the binary, and I think it is done with `cmake -DPORTABLE`) and foregoing `make install` for the `$md_ret_files=()` function.

EDIT: `-DPORTABLE` didn't work, I'll see what else I can dig up.

`-DPORTABLE=On` might be it. At least it made the build files this time; compiling now, don't know when I'll have much chance to test the bin.

**Comment by s1eve-mcdichae1** [comment]
The "PORTABLE" build launched with `data` dir in the same arbitrary dir as the binary, but: it doesn't respond to my gamepad, and the menu screen was only in the top-left quadrant of my display (although the scrolling-clouds background did fill the whole thing so, not sure what's up with that.) Guess I need some additional compile- or run-time options, gonna have to figure that out.

I hope you don't feel like I'm stepping on your toes, here, I'm just trying to contribute whatever I can to the collaborative effort.

**Comment by s1eve-mcdichae1** [comment]
I'm not able to reopen this PR, I guess when I renamed my branch it broke the link between them. I will submit a new one with my current progress.

**Comment by Exarkuniv** [comment]
as i have found with all my building, some binarys cant be pointed to data files. i have done my best with ``/opt/retropie/ports`` being there all my port binarys sit. i did mess with linking the to folders. the one in ``/opt/retropie/ports`` for the binary and then one in ''RetroPie/roms/ports''

im kinds iffy doing it that way, but it did work. dont know what your take is on that.  
i did not mess with my game pad with the game. i can take a look at it and maybe ask the devs and see what they might have to say about it.

no you are not stepping on my toes. 

just explain a little on why you changed what. so that way you are not doing a complete rewrite of what i did. its kinda a waste on both our parts

**Pull request closed without merging**
